### ISSUE TITLE
Lack of some requirements: `dateparser` and `lxml_html_clean`

### ISSUE THREAD

**Issue by indrjo** [Pinperepette/terminal-news#1]
Perhaps you need to add `dateparser` and `lxml_html_clean` among the requirements.

Here you have the logs after `pip install .`:

``` sh
~/terminal-news λ news
Traceback (most recent call last):
  File "/home/indrjo/.local/venv/bin/news", line 5, in <module>
    from terminal_news.news import main
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news.py", line 1, in <module>
    from .news_google.news_google import fetch_articles 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news_google/__init__.py", line 1, in <module>
    from .news_google import NewsGoogle
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news_google/news_google.py", line 2, in <module>
    from .utils import lexical_date_parser, define_date
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news_google/utils.py", line 2, in <module>
    import dateparser
ModuleNotFoundError: No module named 'dateparser'
```

``` sh
~/terminal-news λ news
Traceback (most recent call last):
  File "/home/indrjo/.local/venv/bin/news", line 5, in <module>
    from terminal_news.news import main
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news.py", line 1, in <module>
    from .news_google.news_google import fetch_articles 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news_google/__init__.py", line 1, in <module>
    from .news_google import NewsGoogle
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news_google/news_google.py", line 3, in <module>
    from .scraper import build_response, remove_after_last_fullstop
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/terminal_news/news_google/scraper.py", line 7, in <module>
    from newspaper import Article
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/newspaper/__init__.py", line 10, in <module>
    from .api import (build, build_article, fulltext, hot, languages,
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/newspaper/api.py", line 14, in <module>
    from .article import Article
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/newspaper/article.py", line 15, in <module>
    from . import network
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/newspaper/network.py", line 14, in <module>
    from .configuration import Configuration
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/newspaper/configuration.py", line 15, in <module>
    from .parsers import Parser
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/newspaper/parsers.py", line 12, in <module>
    import lxml.html.clean
  File "/home/indrjo/.local/venv/lib/python3.12/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

**Comment by Pinperepette** [comment]
Hi,

Thank you for your feedback!

I have updated the project to include the missing dependencies dateparser and lxml_html_clean in the installation. Please pull the latest changes and everything should work fine now.

Thanks again for bringing this to my attention, and feel free to let me know if you encounter any further issues!
